import type { z } from "zod";
import type { requirementSchema } from "../../schema";

type RequirementInput = z.input<typeof requirementSchema>;

const skillMin = (skill: string, threshold: number, name: { uz: string; ru: string; en: string }): RequirementInput => ({
  type: "skill_min",
  skill,
  threshold,
  gatesAssessed: true,
  description: {
    uz: `«${name.uz}» koʻnikmasi kamida ${threshold} ball`,
    ru: `Навык «${name.ru}» не ниже ${threshold}`,
    en: `${name.en} at least ${threshold}`,
  },
});

/** Verification rows never gate the ASSESSED level (spec §3.2, P9). */
const verifiedScenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

const practicalAction: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

const ANALYTICS = { uz: "Analitika va oʻlchash", ru: "Аналитика и измерение", en: "Analytics & measurement" };
const RESEARCH = { uz: "Auditoriyani oʻrganish", ru: "Исследование аудитории", en: "Audience research" };
const POSITIONING = { uz: "Pozitsiyalash va xabar", ru: "Позиционирование и месседж", en: "Positioning & messaging" };

/**
 * Spec §8.5. Default level names/thresholds (§8.4) — no `levels` override. composite_min rows are generated by the
 * seeder (P8), never authored. Gates: K1 analytics_measurement, K2 customer_research, K3 positioning_messaging.
 */
export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("analytics_measurement", 10, ANALYTICS)],
  "3": [skillMin("analytics_measurement", 20, ANALYTICS)],
  "4": [skillMin("analytics_measurement", 30, ANALYTICS), skillMin("customer_research", 25, RESEARCH)],
  "5": [skillMin("analytics_measurement", 40, ANALYTICS), skillMin("customer_research", 35, RESEARCH), verifiedScenario], // v5_scenario_campaign_analysis
  "6": [skillMin("analytics_measurement", 50, ANALYTICS), skillMin("customer_research", 45, RESEARCH), skillMin("positioning_messaging", 45, POSITIONING)],
  "7": [skillMin("analytics_measurement", 60, ANALYTICS), skillMin("customer_research", 55, RESEARCH), skillMin("positioning_messaging", 55, POSITIONING), verifiedScenario], // v7_scenario_launch_plan
  "8": [skillMin("analytics_measurement", 70, ANALYTICS), skillMin("customer_research", 65, RESEARCH), skillMin("positioning_messaging", 65, POSITIONING), verifiedScenario, practicalAction], // v8_scenario_strategy_case / v8_portfolio_campaign_results
  "9": [skillMin("analytics_measurement", 80, ANALYTICS), skillMin("customer_research", 75, RESEARCH), skillMin("positioning_messaging", 75, POSITIONING), verifiedScenario, practicalAction], // v9_scenario_brand_strategy_defense / v9_portfolio_marketing_system
};
