import type { z } from "zod";
import type { levelSchema, requirementSchema } from "../../schema";
import { DEFAULT_LEVELS } from "../../levels/default";
import { skills } from "./skills";

type LevelInput = z.input<typeof levelSchema>;
type RequirementInput = z.input<typeof requirementSchema>;

function skillMin(skill: string, threshold: number): RequirementInput {
  const found = skills.find((s) => s.slug === skill);
  if (!found) throw new Error(`accountant levels: unknown skill ${skill}`);
  const { uz, ru, en } = found.name;
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${ru}» не ниже ${threshold}`,
      en: `${en} at least ${threshold}`,
    },
  };
}

const verifiedScenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

const practicalAction: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

/**
 * Doc §10.6. composite_min rows are generated by the seeder (doc §3.2) and are not authored here.
 * K1 double_entry_bookkeeping · K2 financial_statements · K3 accuracy_controls.
 * Verification rows map to slots: L5 v5_scenario_month_close_exercise, L7 v7_scenario_error_hunt_exercise,
 * L8 v8_scenario_reporting_case + v8_portfolio_close_process, L9 v9_scenario_controls_design + v9_portfolio_finance_function.
 */
export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("double_entry_bookkeeping", 10)],
  "3": [skillMin("double_entry_bookkeeping", 20)],
  "4": [skillMin("double_entry_bookkeeping", 30), skillMin("financial_statements", 25)],
  "5": [skillMin("double_entry_bookkeeping", 40), skillMin("financial_statements", 35), verifiedScenario],
  "6": [
    skillMin("double_entry_bookkeeping", 50),
    skillMin("financial_statements", 45),
    skillMin("accuracy_controls", 45),
  ],
  "7": [
    skillMin("double_entry_bookkeeping", 60),
    skillMin("financial_statements", 55),
    skillMin("accuracy_controls", 55),
    verifiedScenario,
  ],
  "8": [
    skillMin("double_entry_bookkeeping", 70),
    skillMin("financial_statements", 65),
    skillMin("accuracy_controls", 65),
    verifiedScenario,
    practicalAction,
  ],
  "9": [
    skillMin("double_entry_bookkeeping", 80),
    skillMin("financial_statements", 75),
    skillMin("accuracy_controls", 75),
    verifiedScenario,
    practicalAction,
  ],
};

/** Doc §10.5: default names and thresholds; levels 8–9 add a "not a certificate" line to `meaning`. */
const NOT_A_CERTIFICATE = {
  uz: "Tasdiqlash LEVEL topshirigʻi orqali amalga oshiriladi va davlat yoki kasbiy sertifikat oʻrnini bosmaydi.",
  ru: "Подтверждение проводится через задание LEVEL и не заменяет государственный или профессиональный сертификат.",
  en: "Verification is a LEVEL task and does not replace a state or professional certificate.",
} as const;

export const levels: LevelInput[] = DEFAULT_LEVELS.map((level) =>
  level.number >= 8
    ? {
        ...level,
        meaning: {
          uz: `${level.meaning.uz} ${NOT_A_CERTIFICATE.uz}`,
          ru: `${level.meaning.ru} ${NOT_A_CERTIFICATE.ru}`,
          en: `${level.meaning.en} ${NOT_A_CERTIFICATE.en}`,
        },
      }
    : { ...level },
);
