import type { z } from "zod";
import type { requirementSchema } from "../../schema";

type RequirementInput = z.input<typeof requirementSchema>;

/**
 * §11.4–§11.5. Designer keeps the default level names and thresholds (no `levels` override).
 * `composite_min` rows are generated by the seeder and never authored (§3.2, P8).
 * Gate skills: K1 visual_fundamentals · K2 brief_problem_framing · K3 typography.
 */
const SKILL_NAMES = {
  visual_fundamentals: { uz: "Vizual asoslar", ru: "Визуальные основы", en: "Visual fundamentals" },
  brief_problem_framing: { uz: "Brif va muammoni aniqlash", ru: "Бриф и постановка задачи", en: "Brief & problem framing" },
  typography: { uz: "Tipografika", ru: "Типографика", en: "Typography" },
} as const;

type GateSkill = keyof typeof SKILL_NAMES;

function skillMin(skill: GateSkill, threshold: number): RequirementInput {
  const n = SKILL_NAMES[skill];
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${n.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${n.ru}» не ниже ${threshold}`,
      en: `${n.en} at least ${threshold}`,
    },
  };
}

const verifiedScenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

const practicalAction: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("visual_fundamentals", 10)],
  "3": [skillMin("visual_fundamentals", 20)],
  "4": [skillMin("visual_fundamentals", 30), skillMin("brief_problem_framing", 25)],
  "5": [skillMin("visual_fundamentals", 40), skillMin("brief_problem_framing", 35), verifiedScenario],
  "6": [skillMin("visual_fundamentals", 50), skillMin("brief_problem_framing", 45), skillMin("typography", 45)],
  "7": [
    skillMin("visual_fundamentals", 60),
    skillMin("brief_problem_framing", 55),
    skillMin("typography", 55),
    verifiedScenario,
  ],
  "8": [
    skillMin("visual_fundamentals", 70),
    skillMin("brief_problem_framing", 65),
    skillMin("typography", 65),
    verifiedScenario,
    practicalAction,
  ],
  "9": [
    skillMin("visual_fundamentals", 80),
    skillMin("brief_problem_framing", 75),
    skillMin("typography", 75),
    verifiedScenario,
    practicalAction,
  ],
};
