import type { z } from "zod";
import type { I18n, levelSchema, requirementSchema } from "../../schema";
import { DEFAULT_LEVELS } from "../../levels/default";

type LevelInput = z.input<typeof levelSchema>;
type RequirementInput = z.input<typeof requirementSchema>;

const SKILL_NAMES: Record<string, I18n> = {
  programming_fundamentals: { uz: "Dasturlash asoslari", ru: "Основы программирования", en: "Programming fundamentals" },
  debugging: { uz: "Xatolarni topish va muammo yechish", ru: "Отладка и решение проблем", en: "Debugging & problem solving" },
  version_control: { uz: "Versiyalarni boshqarish (Git)", ru: "Контроль версий (Git)", en: "Version control (Git)" },
  testing_quality: { uz: "Testlash va kod sifati", ru: "Тестирование и качество кода", en: "Testing & code quality" },
};

function skillMin(skill: keyof typeof SKILL_NAMES, threshold: number): RequirementInput {
  const n = SKILL_NAMES[skill] as I18n;
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${n.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${n.ru}» не ниже ${threshold}`,
      en: `${n.en} at least ${threshold}`,
    },
  };
}

const verifiedScenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

const practicalAction: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

/**
 * Doc 05 §6.5. composite_min rows are generated by the seeder (§3.2) and never authored.
 * Verification rows (gatesAssessed false) map to slots v5_scenario_coding_kata, v7_scenario_design_review,
 * v8_scenario_incident_simulation + v8_portfolio_repository_review, v9_scenario_architecture_defense +
 * v9_portfolio_technical_leadership.
 */
export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("programming_fundamentals", 10)],
  "3": [skillMin("programming_fundamentals", 20)],
  "4": [skillMin("programming_fundamentals", 30), skillMin("debugging", 25), skillMin("version_control", 25)],
  "5": [
    skillMin("programming_fundamentals", 40),
    skillMin("debugging", 35),
    skillMin("version_control", 35),
    verifiedScenario,
  ],
  "6": [skillMin("programming_fundamentals", 50), skillMin("debugging", 45), skillMin("testing_quality", 45)],
  "7": [
    skillMin("programming_fundamentals", 60),
    skillMin("debugging", 55),
    skillMin("testing_quality", 55),
    verifiedScenario,
  ],
  "8": [
    skillMin("programming_fundamentals", 70),
    skillMin("debugging", 65),
    skillMin("testing_quality", 65),
    verifiedScenario,
    practicalAction,
  ],
  "9": [
    skillMin("programming_fundamentals", 80),
    skillMin("debugging", 75),
    skillMin("testing_quality", 75),
    verifiedScenario,
    practicalAction,
  ],
};

const NOT_JOB_GRADE: I18n = {
  uz: "Bu kompetensiya darajasi, ish beruvchi lavozimi emas.",
  ru: "Это уровень компетенций, а не должность у работодателя.",
  en: "This is a competency level, not an employer job grade.",
};

const withNote = (text: I18n): I18n => ({
  uz: `${text.uz} ${NOT_JOB_GRADE.uz}`,
  ru: `${text.ru} ${NOT_JOB_GRADE.ru}`,
  en: `${text.en} ${NOT_JOB_GRADE.en}`,
});

type LevelOverride = Pick<LevelInput, "slug" | "name" | "shortDescription" | "meaning">;

/** Doc 05 §6.4 — developer grade names; default thresholds and verification flags are kept. Level 1 is unchanged. */
const OVERRIDES: Record<number, LevelOverride> = {
  2: {
    slug: "trainee",
    name: { uz: "Stajyor", ru: "Стажёр", en: "Trainee" },
    shortDescription: {
      uz: "Sintaksis va asosiy tushunchalarni bilasiz, kichik vazifalarni yordam bilan bajarasiz.",
      ru: "Вы знаете синтаксис и базовые понятия, небольшие задачи решаете с помощью.",
      en: "You know the syntax and core concepts and solve small tasks with help.",
    },
    meaning: withNote({
      uz: "Kod yoza boshladingiz. Keyingi qadam — kichik vazifalarni mustaqil oxiriga yetkazish.",
      ru: "Вы начали писать код. Следующий шаг — самостоятельно доводить небольшие задачи до конца.",
      en: "You have started writing code. The next step is finishing small tasks on your own.",
    }),
  },
  3: {
    slug: "junior",
    name: { uz: "Junior", ru: "Junior", en: "Junior" },
    shortDescription: {
      uz: "Aniq qoʻyilgan vazifalarni mustaqil bajarasiz, review orqali oʻsasiz.",
      ru: "Вы самостоятельно решаете чётко поставленные задачи и растёте через ревью.",
      en: "You complete well-defined tasks on your own and grow through code review.",
    },
    meaning: withNote({
      uz: "Mavjud kod bazasida ishlay olasiz. Xatolarni tizimli topish va Git bilan ishonchli ishlash hali rivojlanmoqda.",
      ru: "Вы работаете в существующей кодовой базе. Системная отладка и уверенная работа с Git ещё развиваются.",
      en: "You can work in an existing codebase. Systematic debugging and confident Git use are still developing.",
    }),
  },
  4: {
    slug: "junior_plus",
    name: { uz: "Junior+", ru: "Junior+", en: "Junior+" },
    shortDescription: {
      uz: "Kundalik vazifalarni ishonchli yopasiz va xatolarni oʻzingiz topasiz.",
      ru: "Вы надёжно закрываете повседневные задачи и сами находите ошибки.",
      en: "You reliably close everyday tasks and find bugs yourself.",
    },
    meaning: withNote({
      uz: "Natija beryapsiz. Middle darajasi uchun yechimlarni mustaqil tanlash va ularni asoslash kerak.",
      ru: "Вы даёте результат. Для уровня Middle нужно самостоятельно выбирать решения и обосновывать их.",
      en: "You deliver results. To reach Middle, you need to choose solutions independently and justify them.",
    }),
  },
  5: {
    slug: "middle",
    name: { uz: "Middle", ru: "Middle", en: "Middle" },
    shortDescription: {
      uz: "Funksiyani boshidan oxirigacha mustaqil va sifatli yetkazasiz.",
      ru: "Вы самостоятельно и качественно доводите функциональность от начала до конца.",
      en: "You deliver features end to end, independently and to a good standard.",
    },
    meaning: withNote({
      uz: "Murakkab vazifalarni mustaqil hal qilasiz, testlar yozasiz va texnik qarorlaringizni tushuntira olasiz.",
      ru: "Вы самостоятельно решаете сложные задачи, пишете тесты и можете объяснить технические решения.",
      en: "You solve complex tasks independently, write tests and can explain your technical decisions.",
    }),
  },
  6: {
    slug: "middle_plus",
    name: { uz: "Middle+", ru: "Middle+", en: "Middle+" },
    shortDescription: {
      uz: "Modul darajasida qaror qabul qilasiz va kod sifatiga masʼuliyat olasiz.",
      ru: "Вы принимаете решения на уровне модуля и отвечаете за качество кода.",
      en: "You make module-level decisions and take ownership of code quality.",
    },
    meaning: withNote({
      uz: "Tizimning bir qismini yaxshilaysiz va boshqalarga review orqali yoʻnalish berasiz.",
      ru: "Вы улучшаете часть системы и направляете других через ревью.",
      en: "You improve a part of the system and guide others through code review.",
    }),
  },
  7: {
    slug: "senior",
    name: { uz: "Senior", ru: "Senior", en: "Senior" },
    shortDescription: {
      uz: "Murakkab tizimlarda murosalarni koʻrasiz va ishonchli yechim tanlaysiz.",
      ru: "Вы видите компромиссы в сложных системах и выбираете надёжные решения.",
      en: "You see trade-offs in complex systems and choose reliable solutions.",
    },
    meaning: withNote({
      uz: "Nostandart muammolarni hal qilasiz, arxitekturaga taʼsir qilasiz va jamoa sizdan maslahat soʻraydi.",
      ru: "Вы решаете нестандартные задачи, влияете на архитектуру, и команда обращается к вам за советом.",
      en: "You solve non-standard problems, shape architecture and the team comes to you for advice.",
    }),
  },
  8: {
    slug: "lead",
    name: { uz: "Lead", ru: "Lead", en: "Lead" },
    shortDescription: {
      uz: "Jamoaning texnik yoʻnalishi va sifatiga taʼsir qilasiz.",
      ru: "Вы влияете на техническое направление и качество работы команды.",
      en: "You shape a team's technical direction and quality.",
    },
    meaning: withNote({
      uz: "Bu daraja faqat test orqali emas, real amaliy tasdiq orqali beriladi.",
      ru: "Этот уровень присваивается не только по тесту, но и по реальному практическому подтверждению.",
      en: "This level is granted only with real-world verification, not by the test alone.",
    }),
  },
  9: {
    slug: "principal",
    name: { uz: "Principal", ru: "Principal", en: "Principal" },
    shortDescription: {
      uz: "Bir nechta jamoa va tizimlar miqyosidagi texnik qarorlarga taʼsir qilasiz.",
      ru: "Вы влияете на технические решения на уровне нескольких команд и систем.",
      en: "You shape technical decisions across several teams and systems.",
    },
    meaning: withNote({
      uz: "Bu daraja faqat real amaliy tasdiq orqali beriladi.",
      ru: "Этот уровень присваивается только по реальному практическому подтверждению.",
      en: "This level is granted only with real-world verification.",
    }),
  },
};

export const levels: LevelInput[] = DEFAULT_LEVELS.map((level) => ({
  ...level,
  ...(OVERRIDES[level.number] ?? {}),
  requirements: [],
}));
