import type { z } from "zod";
import type { I18n, requirementSchema } from "../../schema";

type RequirementInput = z.input<typeof requirementSchema>;

/**
 * Level requirements for manager (doc §9.5, template §3.3). Default level names and thresholds are kept (§9.4),
 * so no `levels` override is exported. `composite_min` rows are generated by the seeder and never authored (P8);
 * verification rows never gate the ASSESSED level (P9) — levels 8–9 are already capped by requiresVerification.
 */

const SKILL_NAMES: Record<string, I18n> = {
  goal_setting_planning: {
    uz: "Maqsad qoʻyish va rejalashtirish",
    ru: "Постановка целей и планирование",
    en: "Goal-setting & planning",
  },
  feedback_coaching: {
    uz: "Fikr-mulohaza va murabbiylik",
    ru: "Обратная связь и коучинг",
    en: "Feedback & coaching",
  },
  delegation: { uz: "Vakolat berish", ru: "Делегирование", en: "Delegation" },
};

function skillMin(skill: keyof typeof SKILL_NAMES, threshold: number): RequirementInput {
  const name = SKILL_NAMES[skill] as I18n;
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${name.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${name.ru}» не ниже ${threshold}`,
      en: `${name.en} at least ${threshold}`,
    },
  };
}

/** Slots: v5_scenario_one_on_one_simulation, v7_scenario_team_restructure_case, v8_scenario_leadership_simulation, v9_scenario_org_design_defense. */
const verifiedScenario = (skill?: string): RequirementInput => ({
  type: "verified_scenario",
  ...(skill ? { skill } : {}),
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
});

/** Slots: v8_portfolio_team_evidence, v9_portfolio_managers_developed. */
const practicalAction = (): RequirementInput => ({
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
});

export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("goal_setting_planning", 10)],
  "3": [skillMin("goal_setting_planning", 20)],
  "4": [skillMin("goal_setting_planning", 30), skillMin("feedback_coaching", 25)],
  "5": [
    skillMin("goal_setting_planning", 40),
    skillMin("feedback_coaching", 35),
    verifiedScenario("feedback_coaching"),
  ],
  "6": [
    skillMin("goal_setting_planning", 50),
    skillMin("feedback_coaching", 45),
    skillMin("delegation", 45),
  ],
  "7": [
    skillMin("goal_setting_planning", 60),
    skillMin("feedback_coaching", 55),
    skillMin("delegation", 55),
    verifiedScenario(),
  ],
  "8": [
    skillMin("goal_setting_planning", 70),
    skillMin("feedback_coaching", 65),
    skillMin("delegation", 65),
    verifiedScenario(),
    practicalAction(),
  ],
  "9": [
    skillMin("goal_setting_planning", 80),
    skillMin("feedback_coaching", 75),
    skillMin("delegation", 75),
    verifiedScenario(),
    practicalAction(),
  ],
};
