import type { z } from "zod";
import type { levelSchema, requirementSchema } from "../../schema";
import { DEFAULT_LEVELS } from "../../levels/default";

type LevelInput = z.input<typeof levelSchema>;
type RequirementInput = z.input<typeof requirementSchema>;

/**
 * docs/architecture/05-profession-skill-model.md §5.4 — default thresholds; level 4 meaning and levels 5–7 renamed
 * for the founder's job at each stage. Levels 1–3 and 8–9 copy the default text verbatim.
 */
const RENAMED: Partial<Record<number, Partial<LevelInput>>> = {
  4: {
    meaning: {
      uz: "Biznes ishlayapti, lekin asosan sizning shaxsiy kuchingiz hisobiga. Keyingi bosqich — Tizim quruvchi: biznes har bir qadamda sizsiz ham ishlay olishi kerak.",
      ru: "Бизнес работает, но в основном на ваших личных усилиях. Следующий этап — Строитель систем: бизнес должен работать и без вас на каждом шаге.",
      en: "The business runs, but mostly through your personal effort. Next comes System Builder: the business must work without you in every step.",
    },
  },
  5: {
    slug: "system_builder",
    name: { uz: "Tizim quruvchi", ru: "Строитель систем", en: "System Builder" },
    shortDescription: {
      uz: "Biznesingiz tizim asosida ishlaydi.",
      ru: "Ваш бизнес работает на системах.",
      en: "Your business runs on systems.",
    },
    meaning: {
      uz: "Jarayonlar, raqamlar va odamlar har bir qadamda sizsiz ham ishlaydi.",
      ru: "Процессы, цифры и люди работают без вашего участия на каждом шаге.",
      en: "Processes, numbers and people work without you in every step.",
    },
  },
  6: {
    slug: "scaler",
    name: { uz: "Oʻstiruvchi", ru: "Масштабирующий", en: "Scaler" },
    shortDescription: {
      uz: "Ishlayotgan modelni jamoa bilan kengaytirasiz.",
      ru: "Вы масштабируете работающую модель вместе с командой.",
      en: "You scale a working model with a team.",
    },
    meaning: {
      uz: "Unit-iqtisodiyoti maʼlum boʻlgan yoʻnalishlarni jamoa yordamida oʻstirasiz.",
      ru: "Вы растите то, что работает, опираясь на известную юнит-экономику и команду.",
      en: "You grow what works with known unit economics and a team.",
    },
  },
  7: {
    slug: "strategist",
    name: { uz: "Strateg", ru: "Стратег", en: "Strategist" },
    shortDescription: {
      uz: "Bozor va yoʻnalishlarni ongli ravishda tanlaysiz.",
      ru: "Вы осознанно выбираете рынки и направления.",
      en: "You choose markets and directions deliberately.",
    },
    meaning: {
      uz: "Bozorlar va yirik qadamlarni ongli tanlaysiz hamda ular boʻyicha riskni boshqarasiz.",
      ru: "Вы осознанно выбираете рынки и ставки и управляете рисками между ними.",
      en: "You choose markets and bets deliberately and manage risk across them.",
    },
  },
};

export const levels: LevelInput[] = DEFAULT_LEVELS.map((level) => ({ ...level, ...RENAMED[level.number] }));

const SKILL_NAMES = {
  finance: { uz: "Moliyaviy boshqaruv", ru: "Управление финансами", en: "Financial management" },
  operations: { uz: "Operatsion jarayonlar", ru: "Операционные процессы", en: "Operations & processes" },
  sales: { uz: "Savdo", ru: "Продажи", en: "Sales" },
} as const;

/** skill_min gate (§3.3 copy pattern). */
function gate(skill: keyof typeof SKILL_NAMES, threshold: number): RequirementInput {
  const n = SKILL_NAMES[skill];
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${n.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${n.ru}» не ниже ${threshold}`,
      en: `${n.en} at least ${threshold}`,
    },
  };
}

/** verified_scenario — never gates ASSESSED (§3.2, decision P9). */
const scenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

/** practical_action (portfolio) — never gates ASSESSED. */
const evidence: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

/**
 * §5.5 — gate skills K1 finance, K2 operations, K3 sales. composite_min rows are generated by the seeder (P8).
 * Verification slots: L5 v5_scenario_cash_gap_case, L7 v7_scenario_scaling_case,
 * L8 v8_scenario_board_simulation + v8_portfolio_business_evidence, L9 v9_scenario_strategy_defense + v9_portfolio_multi_unit_evidence.
 */
export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [gate("finance", 10)],
  "3": [gate("finance", 20)],
  "4": [gate("finance", 30), gate("operations", 25)],
  "5": [gate("finance", 40), gate("operations", 35), scenario],
  "6": [gate("finance", 50), gate("operations", 45), gate("sales", 45)],
  "7": [gate("finance", 60), gate("operations", 55), gate("sales", 55), scenario],
  "8": [gate("finance", 70), gate("operations", 65), gate("sales", 65), scenario, evidence],
  "9": [gate("finance", 80), gate("operations", 75), gate("sales", 75), scenario, evidence],
};
