import type { z } from "zod";
import type { requirementSchema } from "../../schema";
import { skills } from "./skills";

type RequirementInput = z.input<typeof requirementSchema>;

/**
 * Level requirements (05 §13.5). Default level names and thresholds are kept (§13.4), so no `levels` override.
 * `composite_min` rows are generated by the seeder (P8); verification rows never gate ASSESSED (P9).
 */
function skillMin(skill: string, threshold: number): RequirementInput {
  const found = skills.find((s) => s.slug === skill);
  if (!found) throw new Error(`teacher levels: unknown skill ${skill}`);
  const { name } = found;
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${name.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${name.ru}» не ниже ${threshold}`,
      en: `${name.en} at least ${threshold}`,
    },
  };
}

function verifiedScenario(description: RequirementInput["description"]): RequirementInput {
  return { type: "verified_scenario", threshold: null, gatesAssessed: false, description };
}

function practicalAction(description: RequirementInput["description"]): RequirementInput {
  return { type: "practical_action", threshold: null, gatesAssessed: false, description };
}

export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("lesson_planning", 10)],
  "3": [skillMin("lesson_planning", 20)],
  "4": [skillMin("lesson_planning", 30), skillMin("assessment_feedback", 25)],
  "5": [
    skillMin("lesson_planning", 40),
    skillMin("assessment_feedback", 35),
    // v5_scenario_lesson_plan_critique
    verifiedScenario({
      uz: "Dars rejasini tahlil qilish topshirigʻida koʻnikmani tasdiqlash",
      ru: "Подтвердить навык в задании на разбор плана урока",
      en: "Prove it by critiquing a lesson plan in a practical task",
    }),
  ],
  "6": [
    skillMin("lesson_planning", 50),
    skillMin("assessment_feedback", 45),
    skillMin("instructional_methods", 45),
  ],
  "7": [
    skillMin("lesson_planning", 60),
    skillMin("assessment_feedback", 55),
    skillMin("instructional_methods", 55),
    // v7_scenario_classroom_incidents
    verifiedScenario({
      uz: "Sinfdagi murakkab vaziyatlar boʻyicha amaliy topshiriqda tasdiqlash",
      ru: "Подтвердить навык в задании по сложным ситуациям в классе",
      en: "Prove it in a practical task on difficult classroom situations",
    }),
  ],
  "8": [
    skillMin("lesson_planning", 70),
    skillMin("assessment_feedback", 65),
    skillMin("instructional_methods", 65),
    // v8_scenario_mentor_feedback
    verifiedScenario({
      uz: "Hamkasbning darsiga ustoz sifatida fikr-mulohaza berish topshirigʻi",
      ru: "Задание: дать наставническую обратную связь по уроку коллеги",
      en: "Practical task: give mentor feedback on a colleague's lesson",
    }),
    // v8_portfolio_lesson_evidence
    practicalAction({
      uz: "Real dars rejasi, oʻquvchi ishlari namunalari va refleksiyani taqdim etish (yuz va ismlarsiz)",
      ru: "Предоставить реальный план урока, образцы работ учеников и рефлексию (без лиц и имён)",
      en: "Submit a real lesson plan, student work samples and a reflection (no faces or names)",
    }),
  ],
  "9": [
    skillMin("lesson_planning", 80),
    skillMin("assessment_feedback", 75),
    skillMin("instructional_methods", 75),
    // v9_scenario_curriculum_design
    verifiedScenario({
      uz: "Oʻquv dasturi yoki kurs tuzish boʻyicha amaliy topshiriqda tasdiqlash",
      ru: "Подтвердить навык в задании на разработку учебной программы или курса",
      en: "Prove it by designing a curriculum or course in a practical task",
    }),
    // v9_portfolio_teachers_mentored
    practicalAction({
      uz: "Boshqa oʻqituvchilarga ustozlik qilganingiz haqida dalil taqdim etish",
      ru: "Предоставить подтверждение наставничества других преподавателей",
      en: "Provide evidence of mentoring other teachers",
    }),
  ],
};
