import type { z } from "zod";
import type { I18n, requirementSchema } from "../../schema";

type RequirementInput = z.input<typeof requirementSchema>;

/**
 * Level requirements per docs/architecture/05-profession-skill-model.md §7.5. Default level names and thresholds are
 * kept (doc §7.4 — no rename), so no `levels` override is exported. `composite_min` rows are generated by the seeder
 * (doc §3.2 P8) and are not authored here. Verification rows never gate the ASSESSED level (doc P9).
 */
const SKILL_NAMES: Record<"discovery" | "objection_handling" | "closing", I18n> = {
  discovery: { uz: "Ehtiyojni aniqlash", ru: "Выявление потребностей", en: "Needs discovery" },
  objection_handling: { uz: "Eʼtirozlar bilan ishlash", ru: "Работа с возражениями", en: "Objection handling" },
  closing: { uz: "Bitimni yopish", ru: "Закрытие сделки", en: "Closing" },
};

function skillMin(skill: keyof typeof SKILL_NAMES, threshold: number): RequirementInput {
  const n = SKILL_NAMES[skill];
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${n.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${n.ru}» не ниже ${threshold}`,
      en: `${n.en} at least ${threshold}`,
    },
  };
}

const verifiedScenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

const practicalAction: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("discovery", 10)],
  "3": [skillMin("discovery", 20)],
  "4": [skillMin("discovery", 30), skillMin("objection_handling", 25)],
  // v5_scenario_ai_customer
  "5": [skillMin("discovery", 40), skillMin("objection_handling", 35), verifiedScenario],
  "6": [skillMin("discovery", 50), skillMin("objection_handling", 45), skillMin("closing", 45)],
  // v7_scenario_ai_b2b_negotiation
  "7": [skillMin("discovery", 60), skillMin("objection_handling", 55), skillMin("closing", 55), verifiedScenario],
  // v8_scenario_call_review_coaching + v8_portfolio_pipeline_evidence
  "8": [
    skillMin("discovery", 70),
    skillMin("objection_handling", 65),
    skillMin("closing", 65),
    verifiedScenario,
    practicalAction,
  ],
  // v9_scenario_sales_system_design + v9_portfolio_team_results
  "9": [
    skillMin("discovery", 80),
    skillMin("objection_handling", 75),
    skillMin("closing", 75),
    verifiedScenario,
    practicalAction,
  ],
};
