import type { z } from "zod";
import type { requirementSchema } from "../../schema";

type RequirementInput = z.input<typeof requirementSchema>;

/**
 * §14.5 — default level names and thresholds (no rename for driving_instructor, so no `levels` export).
 * safety_risk_management is gated with ZERO slack from L4 upward (threshold = min_composite). composite_min rows are
 * generated by the seeder and never authored (§3.2). Verification rows never gate ASSESSED (P9).
 */
const SKILL_NAMES = {
  safety_risk_management: { uz: "Xavfsizlik va xavfni boshqarish", ru: "Безопасность и управление рисками", en: "Safety & risk management" },
  clear_commands: { uz: "Aniq koʻrsatmalar berish", ru: "Чёткие команды в машине", en: "Clear in-car commands" },
  traffic_rules_knowledge: { uz: "Yoʻl harakati qoidalarini bilish", ru: "Знание ПДД", en: "Traffic rules knowledge" },
} as const;

type GateSkill = keyof typeof SKILL_NAMES;

const skillMin = (skill: GateSkill, threshold: number): RequirementInput => {
  const n = SKILL_NAMES[skill];
  return {
    type: "skill_min",
    skill,
    threshold,
    gatesAssessed: true,
    description: {
      uz: `«${n.uz}» koʻnikmasi kamida ${threshold} ball`,
      ru: `Навык «${n.ru}» не ниже ${threshold}`,
      en: `${n.en} at least ${threshold}`,
    },
  };
};

const verifiedScenario: RequirementInput = {
  type: "verified_scenario",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Amaliy vaziyatni real topshiriqda tasdiqlash",
    ru: "Подтвердить навык в практическом сценарии",
    en: "Prove it in a practical scenario",
  },
};

const practicalAction: RequirementInput = {
  type: "practical_action",
  threshold: null,
  gatesAssessed: false,
  description: {
    uz: "Real ishdan dalil taqdim etish",
    ru: "Предоставить подтверждение из реальной работы",
    en: "Provide evidence from real work",
  },
};

export const levelRequirements: Record<string, RequirementInput[]> = {
  "2": [skillMin("safety_risk_management", 10)],
  "3": [skillMin("safety_risk_management", 20)],
  "4": [skillMin("safety_risk_management", 35), skillMin("clear_commands", 25)],
  "5": [skillMin("safety_risk_management", 45), skillMin("clear_commands", 35), verifiedScenario],
  "6": [
    skillMin("safety_risk_management", 55),
    skillMin("clear_commands", 45),
    skillMin("traffic_rules_knowledge", 45),
  ],
  "7": [
    skillMin("safety_risk_management", 65),
    skillMin("clear_commands", 55),
    skillMin("traffic_rules_knowledge", 55),
    verifiedScenario,
  ],
  "8": [
    skillMin("safety_risk_management", 75),
    skillMin("clear_commands", 65),
    skillMin("traffic_rules_knowledge", 65),
    verifiedScenario,
    practicalAction,
  ],
  "9": [
    skillMin("safety_risk_management", 85),
    skillMin("clear_commands", 75),
    skillMin("traffic_rules_knowledge", 75),
    verifiedScenario,
    practicalAction,
  ],
};
