import type { ActionInput } from "./_types";

/** Actions for designer.brand_systems. */
export const actions: ActionInput[] = [
  {
    slug: "bs_local_brand_consistency_audit",
    skill: "brand_systems",
    kind: "reflect",
    phase: "foundation",
    durationMinutes: 20,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Mahalliy brendning vizual izchilligini tahlil qiling",
      ru: "Разберите визуальную целостность местного бренда",
      en: "Audit a local brand's visual consistency",
    },
    description: {
      uz: "Bitta mahalliy biznesning 6 ta aloqa nuqtasini toʻplang: peshlavha, ijtimoiy tarmoq postlari, menyu, qadoq va h.k. Logotip, ranglar va shriftlar qayerda bir xil, qayerda farqli ekanini yozing.",
      ru: "Соберите 6 точек контакта одного местного бизнеса: вывеска, посты в соцсетях, меню, упаковка и т. д. Отметьте, где логотип, цвета и шрифты едины, а где расходятся.",
      en: "Collect 6 touchpoints of one local business: signboard, social posts, menu, packaging, etc. Note where logo, colours and fonts match and where they drift.",
    },
    successCriteria: {
      uz: "6 ta aloqa nuqtasi bitta doskada va kamida 3 ta nomuvofiqlik roʻyxati bor.",
      ru: "6 точек контакта собраны на одной доске, есть список минимум из 3 несоответствий.",
      en: "6 touchpoints on one board and a list of at least 3 inconsistencies.",
    },
    why: {
      uz: "Tizim nima uchun kerakligini u yoʻq joyda koʻrish eng tez tushuntiradi.",
      ru: "Зачем нужна система, проще всего понять, увидев, что бывает без неё.",
      en: "Seeing what happens without a system is the quickest way to grasp why one is needed.",
    },
    resources: [],
  },
  {
    slug: "bs_one_page_brand_guide",
    skill: "brand_systems",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Bir sahifalik brend qoidalarini yozing",
      ru: "Напишите бренд-гайд на одну страницу",
      en: "Write a one-page brand guide",
    },
    description: {
      uz: "Oʻz yoki mashq brendingiz uchun: logotipdan foydalanish (atrofdagi boʻsh joy, minimal oʻlcham, taqiqlar), kodlari bilan 4–6 rang, vazifasi koʻrsatilgan 2 ta shrift. Hammasi bir sahifada.",
      ru: "Для своего или учебного бренда: использование логотипа (охранное поле, минимальный размер, запреты), 4–6 цветов с кодами, 2 шрифта с ролями. Всё на одной странице.",
      en: "For your own or a practice brand: logo usage (clear space, minimum size, don'ts), 4–6 colours with codes, 2 typefaces with roles. All on one page.",
    },
    successCriteria: {
      uz: "Boshqa odam shu sahifaga qarab brendga mos post yarata oladi.",
      ru: "Другой человек может по этой странице сделать пост в стиле бренда.",
      en: "Someone else could make an on-brand post using only this page.",
    },
    why: {
      uz: "Qoidalar yozilmasa, brend faqat muallif boshida yashaydi va har yangi ishda buziladi.",
      ru: "Без записанных правил бренд живёт только в голове автора и размывается в каждой новой работе.",
      en: "Unwritten rules live only in the author's head and erode with every new piece.",
    },
    resources: [],
  },
  {
    slug: "bs_extend_identity_new_touchpoint",
    skill: "brand_systems",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Brendni yangi tashuvchiga moslashtiring",
      ru: "Перенесите айдентику на новый носитель",
      en: "Extend an identity to a new touchpoint",
    },
    description: {
      uz: "Mavjud firma uslubini qoidalarda koʻzda tutilmagan yangi tashuvchiga qoʻllang (yetkazib berish paketi, Telegram kanal muqovasi). Faqat qoidalardan foydalaning va qoidalar yetmagan joylarni yozing.",
      ru: "Примените существующий фирменный стиль к новому носителю, не описанному в гайде (пакет доставки, обложка Telegram-канала). Используйте только правила гайда и отметьте, где их не хватило.",
      en: "Apply an existing identity to a touchpoint the guide does not cover (delivery bag, Telegram channel cover). Use only the guide's rules and note where they fell short.",
    },
    successCriteria: {
      uz: "Yangi tashuvchi brendga mos, yetishmagan qoidalar roʻyxati tuzilgan.",
      ru: "Новый носитель в стиле бренда, составлен список недостающих правил.",
      en: "The new touchpoint is on-brand and missing rules are listed.",
    },
    why: {
      uz: "Tizimning kuchi yangi vaziyatda sinaladi. Boʻshliqlarni topish uni rivojlantirishning birinchi qadami.",
      ru: "Сила системы проверяется в новой ситуации. Найти пробелы — первый шаг к её развитию.",
      en: "A system is tested by new situations; finding gaps is the first step to growing it.",
    },
    resources: [],
  },
  {
    slug: "bs_define_design_tokens",
    skill: "brand_systems",
    kind: "apply",
    phase: "application",
    durationMinutes: 50,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Rang va boʻshliqlar uchun dizayn tokenlarini belgilang",
      ru: "Задайте дизайн-токены для цветов и отступов",
      en: "Define design tokens for colour and spacing",
    },
    description: {
      uz: "Real mahsulotdagi qoʻlda yozilgan qiymatlarni nomlangan tokenlarga aylantiring (color.primary, color.text.muted, space.8 va h.k.). Tokenlarni hujjatlang va 2 ta ekranga qoʻllang.",
      ru: "Замените захардкоженные значения в реальном продукте именованными токенами (color.primary, color.text.muted, space.8 и т. д.). Задокументируйте их и примените к 2 экранам.",
      en: "Replace hard-coded values in a live product with named tokens (color.primary, color.text.muted, space.8, etc.). Document them and apply them to 2 screens.",
    },
    successCriteria: {
      uz: "Tokenlar nomi va qiymati bilan hujjatlangan, 2 ta ekran faqat tokenlardan foydalanadi.",
      ru: "Токены задокументированы с именами и значениями, 2 экрана используют только токены.",
      en: "Tokens are documented with names and values; 2 screens use tokens only.",
    },
    why: {
      uz: "Tokenlar brend qoidalarini dizayn va kod orasida bir xil tilga aylantiradi.",
      ru: "Токены превращают правила бренда в общий язык дизайна и кода.",
      en: "Tokens turn brand rules into a shared language between design and code.",
    },
    resources: [],
  },
  {
    slug: "bs_guide_handover_test",
    skill: "brand_systems",
    kind: "verify",
    phase: "verification",
    durationMinutes: 40,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Brend qoidalarini boshqa odam orqali sinab koʻring",
      ru: "Проверьте бренд-гайд руками другого человека",
      en: "Test your brand guide through someone else",
    },
    description: {
      uz: "Qoidalar va shablonlarni hamkasb yoki dizayner boʻlmagan odamga bering. Undan sizning yordamingizsiz bitta post yoki ekran yaratishni soʻrang. Brenddan chetlanishlarni belgilang.",
      ru: "Передайте гайд и шаблоны коллеге или не-дизайнеру. Попросите без вашей помощи сделать один пост или экран. Отметьте отклонения от бренда.",
      en: "Give your guide and templates to a colleague or non-designer. Ask them to make one post or screen without your help. Mark any off-brand deviations.",
    },
    successCriteria: {
      uz: "Natijada 2 tadan koʻp chetlanish yoʻq, har bir chetlanish qoidalarga tuzatish sifatida kiritilgan.",
      ru: "В результате не больше 2 отклонений, каждое превращено в правку гайда.",
      en: "No more than 2 deviations, and each one becomes a guide fix.",
    },
    why: {
      uz: "Tizim faqat boshqalar uni muallifsiz ishlata olsa ishlaydi.",
      ru: "Система работает, только если другие могут пользоваться ею без автора.",
      en: "A system only works if others can use it without its author.",
    },
    resources: [],
  },
];
