import type { ActionInput } from "./_types";

/** Actions for designer.brief_problem_framing (gate K2). */
export const actions: ActionInput[] = [
  {
    slug: "bf_brief_question_checklist",
    skill: "brief_problem_framing",
    kind: "learn",
    phase: "foundation",
    durationMinutes: 15,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Brif uchun 5 ta asosiy savol roʻyxatini tuzing",
      ru: "Составьте чек-лист из 5 вопросов для брифа",
      en: "Write a 5-question brief checklist",
    },
    description: {
      uz: "Oʻzingiz uchun roʻyxat yozing: maqsad (nima oʻzgarishi kerak), auditoriya, qayerda ishlatiladi, cheklovlar (muddat, byudjet, formatlar), muvaffaqiyat qanday oʻlchanadi. Har biriga bitta aniqlashtiruvchi savol qoʻshing.",
      ru: "Напишите себе чек-лист: цель (что должно измениться), аудитория, где будет использоваться, ограничения (срок, бюджет, форматы), как измерить успех. К каждому пункту добавьте уточняющий вопрос.",
      en: "Write your own checklist: goal (what should change), audience, where it will be used, constraints (deadline, budget, formats), how success is measured. Add one follow-up question to each.",
    },
    successCriteria: {
      uz: "5 ta savol va aniqlashtiruvchi savollardan iborat qayta ishlatiladigan roʻyxat tayyor.",
      ru: "Готов многоразовый чек-лист из 5 вопросов с уточнениями.",
      en: "A reusable checklist of 5 questions with follow-ups is ready.",
    },
    why: {
      uz: "Koʻp qayta ishlashlar noaniq brifdan boshlanadi. Roʻyxat notoʻgʻri muammo ustida ishlashning oldini oladi.",
      ru: "Многие переделки начинаются с размытого брифа. Чек-лист не даёт решать не ту задачу.",
      en: "Many redesign loops start with a vague brief; a checklist stops you solving the wrong problem.",
    },
    resources: [],
  },
  {
    slug: "bf_rewrite_vague_request",
    skill: "brief_problem_framing",
    kind: "practice",
    phase: "practice",
    durationMinutes: 20,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Noaniq soʻrovni aniq vazifaga aylantiring",
      ru: "Превратите размытый запрос в чёткую задачу",
      en: "Turn a vague request into a clear problem",
    },
    description: {
      uz: "«Chiroyli logotip qiling» yoki «Saytni zamonaviy qiling» kabi soʻrovni oling. Nima yetishmasligini va qanday savollar berishingizni yozing. Soʻng 3 jumlalik vazifa taʼrifini tuzing, taxminlarni alohida belgilang.",
      ru: "Возьмите запрос вроде «Сделайте красивый логотип» или «Сделайте сайт современным». Выпишите, чего не хватает и какие вопросы вы зададите. Затем сформулируйте задачу в 3 предложениях, отметив допущения.",
      en: "Take a request like 'Make a nice logo' or 'Make the site modern'. Write what is missing and which questions you would ask. Then write a 3-sentence problem statement with assumptions marked.",
    },
    successCriteria: {
      uz: "Vazifa taʼrifida maqsad, auditoriya va muvaffaqiyat mezoni bor, taxminlar belgilangan.",
      ru: "В формулировке есть цель, аудитория и критерий успеха, допущения отмечены.",
      en: "The statement names goal, audience and success measure, with assumptions labelled.",
    },
    why: {
      uz: "Mijoz koʻpincha yechimni aytadi, muammoni emas. Uni muammoga qaytarish dizaynerning asosiy vazifasi.",
      ru: "Заказчик чаще называет решение, а не проблему. Вернуть разговор к проблеме — ключевая задача дизайнера.",
      en: "Clients usually state a solution, not the problem; getting back to the problem is core designer work.",
    },
    resources: [],
  },
  {
    slug: "bf_define_success_metric",
    skill: "brief_problem_framing",
    kind: "practice",
    phase: "practice",
    durationMinutes: 25,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Loyiha uchun muvaffaqiyat mezonini belgilang",
      ru: "Определите критерий успеха проекта",
      en: "Define a success measure for a project",
    },
    description: {
      uz: "Joriy loyiha uchun 1–2 ta kuzatiladigan natija yozing (masalan, menyu orqali Click/Payme buyurtmalari koʻpayishi yoki roʻyxatdan oʻtish boʻyicha savollar kamayishi) va ishga tushgach uni qanday tekshirishingizni belgilang.",
      ru: "Для текущего проекта запишите 1–2 наблюдаемых результата (например, больше заказов через Click/Payme из меню или меньше вопросов о регистрации) и как вы проверите их после запуска.",
      en: "For a current project, write 1–2 observable outcomes (e.g. more Click/Payme orders from the menu, fewer sign-up questions to support) and how you will check them after launch.",
    },
    successCriteria: {
      uz: "Oʻlchanadigan mezon va tekshirish sanasi mijoz yoki jamoa bilan kelishilgan.",
      ru: "Измеримый критерий и дата проверки согласованы с заказчиком или командой.",
      en: "A measurable criterion and a check date are agreed with the client or team.",
    },
    why: {
      uz: "Muvaffaqiyat mezoni boʻlmasa, muhokama didlar bahsiga aylanadi. Mezon qarorlarni maqsadga bogʻlaydi.",
      ru: "Без критерия успеха обсуждение превращается в спор о вкусах. Критерий привязывает решения к цели.",
      en: "Without a success measure, review becomes a taste debate; the measure ties decisions to the goal.",
    },
    resources: [],
  },
  {
    slug: "bf_run_brief_interview",
    skill: "brief_problem_framing",
    kind: "apply",
    phase: "application",
    durationMinutes: 40,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Real mijoz bilan brif suhbatini oʻtkazing",
      ru: "Проведите брифинг с реальным заказчиком",
      en: "Run a brief interview with a real client",
    },
    description: {
      uz: "Navbatdagi topshiriqdan oldin roʻyxatingiz asosida 20 daqiqalik suhbat oʻtkazing. Har bir talab ortidagi «nima uchun»ni soʻrang. Oxirida xulosani ovoz chiqarib takrorlang va yozma xulosani yuboring.",
      ru: "Перед следующей задачей проведите 20-минутный разговор по чек-листу. За каждым пожеланием уточняйте «зачем». В конце проговорите резюме и отправьте его письменно.",
      en: "Before your next task, hold a 20-minute call using your checklist. Ask 'why' behind each request. At the end, read back a summary and send it in writing.",
    },
    successCriteria: {
      uz: "Yozma brif mijoz tomonidan xabar orqali tasdiqlangan.",
      ru: "Письменный бриф подтверждён заказчиком в сообщении.",
      en: "The written brief is confirmed by the client in a message.",
    },
    why: {
      uz: "Tasdiqlangan brif keyingi tanqid va taqdimot uchun tayanch boʻladi va qayta ishlashni kamaytiradi.",
      ru: "Подтверждённый бриф становится опорой для критики и презентации и сокращает переделки.",
      en: "A confirmed brief anchors later critique and presentation and cuts rework.",
    },
    resources: [],
  },
  {
    slug: "bf_brief_vs_result_review",
    skill: "brief_problem_framing",
    kind: "verify",
    phase: "verification",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Tugagan ishni brif bilan solishtirib tekshiring",
      ru: "Сверьте готовую работу с брифом",
      en: "Check a finished project against its brief",
    },
    description: {
      uz: "Tugagan loyihani oling. Brifdagi har bir talabni yozing va baholang: bajarildi, qisman, bajarilmadi — dalil bilan. Muammo jarayonda qayerda oʻzgarganini va nima sababdan ekanini belgilang.",
      ru: "Возьмите завершённый проект. Выпишите каждое требование брифа и оцените: выполнено, частично, нет — с доказательством. Отметьте, где по ходу работы изменилась задача и почему.",
      en: "Take a finished project. List every brief requirement and rate it met, partly or not met, with evidence. Note where the problem shifted mid-way and why.",
    },
    successCriteria: {
      uz: "Barcha talablar baholangan jadval va keyingi brif uchun 1 ta xulosa bor.",
      ru: "Есть таблица со всеми оценёнными требованиями и 1 вывод для следующего брифа.",
      en: "A table rates every requirement and gives 1 lesson for the next brief.",
    },
    why: {
      uz: "Natijani brifga qarshi tekshirish muammoni qanchalik toʻgʻri qoʻyganingizni dalil bilan koʻrsatadi.",
      ru: "Сверка результата с брифом доказательно показывает, насколько верно была поставлена задача.",
      en: "Checking results against the brief gives evidence of how well you framed the problem.",
    },
    resources: [],
  },
];
