import type { ActionInput } from "./_types";

/** Actions for designer.design_tools. Tool-agnostic on purpose: no product-specific features are assumed. */
export const actions: ActionInput[] = [
  {
    slug: "dt_learn_ten_shortcuts",
    skill: "design_tools",
    kind: "learn",
    phase: "foundation",
    durationMinutes: 15,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Eng koʻp ishlatadigan 10 ta tezkor tugmani oʻrganing",
      ru: "Выучите 10 горячих клавиш для частых действий",
      en: "Learn shortcuts for your 10 most-used actions",
    },
    description: {
      uz: "Eng koʻp bajaradigan 10 ta amalni yozing (guruhlash, tekislash, nusxalash, kattalashtirish va h.k.). Dasturingizdan ularning tezkor tugmalarini toping, roʻyxatni ekran yoniga qoʻying va bugun faqat ular bilan ishlang.",
      ru: "Выпишите 10 действий, которые делаете чаще всего (группировка, выравнивание, дублирование, масштаб и т. д.). Найдите их сочетания клавиш в своей программе, держите список рядом и сегодня работайте только ими.",
      en: "List the 10 actions you do most (group, align, duplicate, zoom, etc.). Find their shortcuts in your tool, keep the list next to the screen and use only them today.",
    },
    successCriteria: {
      uz: "Kun oxirida 10 ta amalning barchasini menyusiz bajarasiz.",
      ru: "К концу дня все 10 действий выполняются без меню.",
      en: "By the end of the day you do all 10 actions without menus.",
    },
    why: {
      uz: "Dasturdagi ortiqcha harakatlar diqqatni dizayn qarorlaridan oladi. Tezlik fikrlash uchun vaqt ochadi.",
      ru: "Лишние движения в программе отнимают внимание от дизайнерских решений. Скорость освобождает время на мышление.",
      en: "Tool friction steals attention from design decisions; speed frees time for thinking.",
    },
    resources: [],
  },
  {
    slug: "dt_clean_up_work_file",
    skill: "design_tools",
    kind: "practice",
    phase: "practice",
    durationMinutes: 25,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Bitta ish faylini tartibga keltiring",
      ru: "Наведите порядок в одном рабочем файле",
      en: "Clean up one working file",
    },
    description: {
      uz: "Qatlam va freymlarga maʼnoli nom bering, yashirin keraksiz elementlarni oʻchiring, sahifalarga ajrating (jarayon, yakuniy, arxiv). Ranglar va matnlar uchun stillardan foydalaning.",
      ru: "Дайте слоям и фреймам понятные имена, удалите скрытый мусор, разложите по страницам (в работе, финал, архив). Используйте стили для цветов и текста.",
      en: "Give layers and frames meaningful names, delete hidden junk, split into pages (work, final, archive). Use styles for colours and text.",
    },
    successCriteria: {
      uz: "Hamkasb yakuniy versiyani soʻramasdan 1 daqiqa ichida topadi.",
      ru: "Коллега находит финальную версию без вопросов меньше чем за минуту.",
      en: "A colleague finds the final version in under a minute without asking.",
    },
    why: {
      uz: "Tartibli fayl topshirish va jamoaviy ishni tezlashtiradi, xatoli versiyani yuborish xavfini kamaytiradi.",
      ru: "Аккуратный файл ускоряет передачу и командную работу и снижает риск отправить не ту версию.",
      en: "A tidy file speeds up handoff and teamwork and lowers the risk of sending the wrong version.",
    },
    resources: [],
  },
  {
    slug: "dt_responsive_card_build",
    skill: "design_tools",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Matn uzunligiga moslashadigan kartochka quring",
      ru: "Соберите карточку, которая подстраивается под текст",
      en: "Build a card that adapts to its content",
    },
    description: {
      uz: "Avtomatik joylashuv va bogʻlanishlar (constraints) yordamida kartochka quring. U uzun ruscha va qisqa oʻzbekcha sarlavhaga hamda 2 xil kenglikka buzilmasdan moslashsin.",
      ru: "С помощью авторазметки и привязок (constraints) соберите карточку, которая без поломок подстраивается под длинный русский и короткий узбекский заголовок и под 2 разные ширины.",
      en: "Using auto layout and constraints, build a card that adapts without breaking to a long Russian and a short Uzbek title and to 2 different widths.",
    },
    successCriteria: {
      uz: "Kartochka 3 xil matn uzunligi va 2 kenglikda buzilmaydi.",
      ru: "Карточка не ломается при 3 длинах текста и 2 ширинах.",
      en: "The card holds up with 3 text lengths and 2 widths.",
    },
    why: {
      uz: "Moslashuvchan tuzilmalar qoʻlda tuzatishga ketadigan vaqtni tejaydi va setkalarni amalda qoʻllashni osonlashtiradi.",
      ru: "Адаптивные структуры экономят время на ручных правках и делают сетки практичными.",
      en: "Responsive structures save manual fixing time and make grids practical.",
    },
    resources: [],
  },
  {
    slug: "dt_turn_repeats_into_components",
    skill: "design_tools",
    kind: "apply",
    phase: "application",
    durationMinutes: 45,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Takrorlanuvchi elementlarni komponentga aylantiring",
      ru: "Превратите повторяющиеся элементы в компоненты",
      en: "Turn repeated elements into components",
    },
    description: {
      uz: "Joriy loyihada 3 martadan koʻp takrorlanadigan elementlarni toping (tugma, kartochka). Ulardan variantli komponent yarating va nusxalarni almashtiring. Bitta xususiyatni oʻzgartirib, hamma joyda yangilanishini tekshiring.",
      ru: "Найдите в текущем проекте элементы, повторяющиеся больше 3 раз (кнопки, карточки). Сделайте из них компоненты с вариантами и замените копии. Измените одно свойство и проверьте, что обновилось везде.",
      en: "Find elements repeated 3+ times in a live project (buttons, cards). Make them components with variants and replace the copies. Change one property and check it updates everywhere.",
    },
    successCriteria: {
      uz: "Bitta oʻzgarish barcha nusxalarni yangilaydi, ajratilgan nusxa qolmagan.",
      ru: "Одна правка обновляет все экземпляры, отвязанных копий не осталось.",
      en: "One edit updates every instance and no detached copies remain.",
    },
    why: {
      uz: "Komponentlar izchillik va tezlikni taʼminlaydi hamda brend tizimlari va topshirish uchun asos boʻladi.",
      ru: "Компоненты дают единообразие и скорость и служат основой для дизайн-систем и передачи макетов.",
      en: "Components give consistency and speed and underpin design systems and handoff.",
    },
    resources: [],
  },
  {
    slug: "dt_timed_rebuild_benchmark",
    skill: "design_tools",
    kind: "verify",
    phase: "verification",
    durationMinutes: 20,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Standart ekranni vaqt bilan yigʻib, natijani yozing",
      ru: "Соберите типовой экран на время и запишите результат",
      en: "Time yourself rebuilding a standard screen",
    },
    description: {
      uz: "Eskizdan standart ekran yoki bannerni vaqtni oʻlchab yigʻing. Vaqt va fayl tartibini (nomlar, stillar, komponentlar) yozing. Bir haftadan soʻng xuddi shu vazifani takrorlab, solishtiring.",
      ru: "Соберите по эскизу типовой экран или баннер, засекая время. Запишите время и состояние файла (имена, стили, компоненты). Через неделю повторите ту же задачу и сравните.",
      en: "Build a standard screen or banner from a sketch while timing yourself. Record time and file tidiness (names, styles, components). Repeat the same task in a week and compare.",
    },
    successCriteria: {
      uz: "2 ta urinish vaqti yozilgan, ikkinchisi sifat pasaymagan holda tezroq.",
      ru: "Записано время 2 попыток, вторая быстрее без потери качества.",
      en: "Two timed runs logged; the second is faster at the same quality.",
    },
    why: {
      uz: "Vaqt oʻlchovi dasturni bilish darajasini his emas, raqam bilan koʻrsatadi.",
      ru: "Замер времени показывает владение инструментом цифрой, а не ощущением.",
      en: "Timing shows tool fluency as a number rather than a feeling.",
    },
    resources: [],
  },
];
