import type { ActionInput } from "./_types";

/** Actions for designer.interaction_ux. */
export const actions: ActionInput[] = [
  {
    slug: "ix_map_signup_flow",
    skill: "interaction_ux",
    kind: "learn",
    phase: "foundation",
    durationMinutes: 20,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Roʻyxatdan oʻtish ssenariysini sxemada chizing",
      ru: "Нарисуйте схему сценария регистрации",
      en: "Map a real sign-up flow",
    },
    description: {
      uz: "Real ilovaning roʻyxatdan oʻtish yoki buyurtma berish jarayonini tanlang. Har ekranni toʻrtburchak, har harakatni strelka bilan chizing. Xatolik va orqaga qaytish yoʻllarini ham qoʻshing.",
      ru: "Выберите в реальном приложении сценарий регистрации или заказа. Нарисуйте каждый экран прямоугольником, каждое действие — стрелкой. Добавьте ветки ошибок и возврата назад.",
      en: "Pick a real app's sign-up or ordering flow. Draw each screen as a box and each action as an arrow. Include error and back paths.",
    },
    successCriteria: {
      uz: "Sxemada asosiy yoʻl va kamida 2 ta xato yoki muqobil yoʻl bor.",
      ru: "На схеме есть основной путь и минимум 2 ветки ошибок или альтернатив.",
      en: "The map shows the happy path plus at least 2 error or alternative paths.",
    },
    why: {
      uz: "Interfeys alohida ekranlar emas, balki ssenariy. Sxema yoʻqolgan qadamlarni oldindan koʻrsatadi.",
      ru: "Интерфейс — это сценарий, а не набор экранов. Схема заранее показывает пропущенные шаги.",
      en: "An interface is a flow, not a set of screens; mapping it exposes missing steps early.",
    },
    resources: [],
  },
  {
    slug: "ix_component_states_set",
    skill: "interaction_ux",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Tugma va maydonning barcha holatlarini chizing",
      ru: "Нарисуйте все состояния кнопки и поля ввода",
      en: "Design every state of a button and input",
    },
    description: {
      uz: "Tugma va matn kiritish maydoni uchun quyidagi holatlarni chizing: oddiy, bosilgan, fokusda, faol emas, yuklanmoqda, xato, muvaffaqiyat. Xato matni muammoni qanday tuzatishni aytsin.",
      ru: "Для кнопки и поля ввода нарисуйте состояния: обычное, нажатое, в фокусе, неактивное, загрузка, ошибка, успех. Текст ошибки должен объяснять, как её исправить.",
      en: "For a button and a text input, design: default, pressed, focus, disabled, loading, error and success. Error text should say how to fix the problem.",
    },
    successCriteria: {
      uz: "Har ikki element uchun 7 ta holat tayyor, xato matni yechimni koʻrsatadi.",
      ru: "Для обоих элементов готовы 7 состояний, текст ошибки подсказывает решение.",
      en: "All 7 states exist for both elements and error text points to a fix.",
    },
    why: {
      uz: "Holatlar yetishmasligi dasturchiga topshirishdagi eng keng tarqalgan boʻshliq. Foydalanuvchi ham aynan shu yerda adashadi.",
      ru: "Пропущенные состояния — самый частый пробел при передаче в разработку, и пользователь теряется именно там.",
      en: "Missing states are the most common handoff gap, and that is exactly where users get lost.",
    },
    resources: [],
  },
  {
    slug: "ix_accessibility_pass",
    skill: "interaction_ux",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Ekranni qulaylik (accessibility) boʻyicha tekshiring",
      ru: "Проверьте экран на доступность",
      en: "Run an accessibility pass on one screen",
    },
    description: {
      uz: "Bitta ekranni tekshiring: bosiladigan elementlar kamida 44×44 pt, matn kontrasti yetarli, maʼlumot faqat rang bilan berilmagan, fokus tartibi mantiqiy, matn 200% kattalashganda buzilmaydi.",
      ru: "Проверьте один экран: зоны нажатия не меньше 44×44 pt, контраст текста достаточный, смысл передаётся не только цветом, порядок фокуса логичен, при увеличении текста до 200% ничего не ломается.",
      en: "Check one screen: tap targets at least 44×44 pt, enough text contrast, meaning not carried by colour alone, logical focus order, nothing breaks at 200% text size.",
    },
    successCriteria: {
      uz: "Roʻyxatdagi har bir muammo tuzatilgan yoki sababi bilan qayd etilgan.",
      ru: "Каждая найденная проблема исправлена или записана с причиной.",
      en: "Every issue found is fixed or logged with a reason.",
    },
    why: {
      uz: "Qulay interfeys hamma uchun, jumladan koʻrishi zaif yoki shoshib turgan foydalanuvchilar uchun ham ishlaydi.",
      ru: "Доступный интерфейс работает для всех, включая людей со слабым зрением и тех, кто спешит.",
      en: "Accessible interfaces work for everyone, including people with low vision or in a hurry.",
    },
    resources: [],
  },
  {
    slug: "ix_empty_error_loading_states",
    skill: "interaction_ux",
    kind: "apply",
    phase: "application",
    durationMinutes: 45,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Real ekran uchun boʻsh, yuklanish va xato holatlarini yarating",
      ru: "Создайте пустое, загрузочное и ошибочное состояния экрана",
      en: "Design empty, loading and error states for a live screen",
    },
    description: {
      uz: "Joriy mahsulot ekrani uchun 4 holat yarating: birinchi foydalanishdagi boʻsh holat, yuklanish, internet yoʻq, server xatosi. Har birida foydalanuvchi keyingi qadamni bilsin. Dasturchi bilan koʻrib chiqing.",
      ru: "Для экрана текущего продукта создайте 4 состояния: пустое при первом входе, загрузка, нет интернета, ошибка сервера. В каждом пользователь должен понимать следующий шаг. Обсудите с разработчиком.",
      en: "For a live product screen, design 4 states: first-use empty, loading, no internet and server error. Each must show the next step. Review them with a developer.",
    },
    successCriteria: {
      uz: "4 holat tayyor, har birida aniq harakat tugmasi bor, dasturchi koʻrib chiqqan.",
      ru: "Готовы 4 состояния, в каждом есть понятное действие, разработчик их посмотрел.",
      en: "4 states ready, each with a clear action, reviewed by a developer.",
    },
    why: {
      uz: "Foydalanuvchi tajribasi koʻpincha ideal holatda emas, chekka holatlarda buziladi.",
      ru: "Опыт пользователя чаще ломается не в идеальном сценарии, а в пограничных состояниях.",
      en: "User experience usually breaks in edge states, not on the happy path.",
    },
    resources: [],
  },
  {
    slug: "ix_measure_task_steps",
    skill: "interaction_ux",
    kind: "verify",
    phase: "verification",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Ssenariy samaradorligini qadam va vaqt bilan oʻlchang",
      ru: "Измерьте эффективность сценария шагами и временем",
      en: "Measure a flow in steps and time",
    },
    description: {
      uz: "Asosiy vazifa (masalan, buyurtmani toʻlash) uchun qayta dizayndan oldin va keyin qadamlar va bosishlar sonini sanang. 2 kishi bilan sinab, vaqtni oʻlchang.",
      ru: "Посчитайте число шагов и нажатий в ключевой задаче (например, оплата заказа) до и после редизайна. Проверьте с 2 людьми и засеките время.",
      en: "Count steps and taps for a key task (e.g. paying for an order) before and after your redesign. Test with 2 people and time it.",
    },
    successCriteria: {
      uz: "Raqamlar yozilgan: qadamlar yoki vaqt kamaygan, yangi xato paydo boʻlmagan.",
      ru: "Цифры записаны: шагов или времени стало меньше, новых ошибок нет.",
      en: "Numbers recorded: fewer steps or less time, and no new errors.",
    },
    why: {
      uz: "Raqamlar UX qarori didga emas, natijaga asoslanganini koʻrsatadi.",
      ru: "Цифры показывают, что UX-решение основано на результате, а не на вкусе.",
      en: "Numbers show a UX decision rests on outcomes, not taste.",
    },
    resources: [],
  },
];
