import type { ActionInput } from "./_types";

/** Actions for designer.layout_grids. */
export const actions: ActionInput[] = [
  {
    slug: "lg_reverse_engineer_grid",
    skill: "layout_grids",
    kind: "learn",
    phase: "foundation",
    durationMinutes: 15,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Tayyor sayt yoki ilovaning setkasini chizib chiqing",
      ru: "Восстановите сетку готового сайта или приложения",
      en: "Reverse-engineer the grid of an existing screen",
    },
    description: {
      uz: "Yangiliklar sayti yoki ilova ekranining skrinshotini oling. Uning ustiga ustunlar, chetki maydonlar va ustunlar orasidagi boʻshliqni chizing. Takrorlanadigan boʻshliq oʻlchamlarini yozib qoʻying.",
      ru: "Сделайте скриншот новостного сайта или экрана приложения. Нарисуйте поверх колонки, поля и межколонные промежутки. Выпишите повторяющиеся значения отступов.",
      en: "Screenshot a news site or app screen. Draw its columns, margins and gutters on top. Write down the spacing values that repeat.",
    },
    successCriteria: {
      uz: "Skrinshotda ustunlar va chetlar belgilangan, kamida 3 ta takroriy boʻshliq oʻlchami yozilgan.",
      ru: "На скриншоте отмечены колонки и поля, выписаны минимум 3 повторяющихся отступа.",
      en: "Columns and margins are marked and at least 3 repeated spacing values are noted.",
    },
    why: {
      uz: "Setkani oʻzingiz qurishdan oldin uni tayyor ishda koʻrish uning mantiqini tushunishga yordam beradi.",
      ru: "Увидеть сетку в готовой работе — самый быстрый путь понять её логику до того, как строить свою.",
      en: "Spotting a grid in finished work is the fastest way to grasp its logic before building your own.",
    },
    resources: [],
  },
  {
    slug: "lg_spacing_scale_8pt",
    skill: "layout_grids",
    kind: "practice",
    phase: "practice",
    durationMinutes: 25,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Bitta sahifani 8 pikselli boʻshliq tizimiga oʻtkazing",
      ru: "Переведите страницу на шаг отступов 8 px",
      en: "Move one page to an 8-px spacing system",
    },
    description: {
      uz: "Oʻz maketingizdagi barcha tasodifiy boʻshliqlarni 8 ga (yoki 4 ga) karrali qiymatlarga almashtiring. Bir-biriga bogʻliq elementlarni yaqinroq, alohida guruhlarni uzoqroq joylashtiring.",
      ru: "Замените все случайные отступы в своём макете на значения, кратные 8 (или 4). Связанные элементы поставьте ближе, отдельные группы — дальше друг от друга.",
      en: "Replace every random spacing in your layout with multiples of 8 (or 4). Put related items closer together and separate groups further apart.",
    },
    successCriteria: {
      uz: "Har bir boʻshliq shkaladan olingan, bogʻliq elementlar koʻzga guruh boʻlib koʻrinadi.",
      ru: "Каждый отступ взят из шкалы, связанные элементы визуально читаются как группы.",
      en: "Every spacing comes from the scale and related items read as groups.",
    },
    why: {
      uz: "Boʻshliq tizimi yaqinlik tamoyilini amalda qoʻllaydi va maketni tartibli hamda qayta ishlatiladigan qiladi.",
      ru: "Система отступов воплощает принцип близости и делает макет аккуратным и воспроизводимым.",
      en: "A spacing system applies the proximity principle and makes layouts tidy and repeatable.",
    },
    resources: [],
  },
  {
    slug: "lg_modular_catalog_page",
    skill: "layout_grids",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Modulli setkada katalog sahifasini yigʻing",
      ru: "Соберите страницу каталога на модульной сетке",
      en: "Build a catalogue page on a modular grid",
    },
    description: {
      uz: "12 ustunli yoki modulli setka quring. Rasm, nom va narxli turli oʻlchamdagi kartochkalarni joylashtiring: ikkita katta, toʻrtta oʻrta, bir nechta kichik. Barcha elementlar ustun va qatorlarga tayansin.",
      ru: "Постройте 12-колоночную или модульную сетку. Разместите карточки разного размера с фото, названием и ценой: две крупные, четыре средние, несколько маленьких. Все элементы должны опираться на колонки и ряды.",
      en: "Set up a 12-column or modular grid. Place cards of different sizes with image, name and price: two large, four medium, several small. Every element should sit on columns and rows.",
    },
    successCriteria: {
      uz: "Barcha elementlar setkaga bogʻlangan, sahifa xilma-xil, lekin izchil koʻrinadi.",
      ru: "Все элементы привязаны к сетке, страница разнообразна, но цельна.",
      en: "All elements snap to the grid; the page is varied yet consistent.",
    },
    why: {
      uz: "Modulli setka murakkab kontentni tartibsizliksiz joylashtirish imkonini beradi.",
      ru: "Модульная сетка позволяет размещать сложный контент без хаоса.",
      en: "Modular grids let you handle complex content without chaos.",
    },
    resources: [],
  },
  {
    slug: "lg_adapt_three_formats",
    skill: "layout_grids",
    kind: "apply",
    phase: "application",
    durationMinutes: 50,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Bitta kontentni 3 ta formatga moslashtiring",
      ru: "Адаптируйте один контент под 3 формата",
      en: "Adapt one piece of content to 3 formats",
    },
    description: {
      uz: "Real loyiha kontentini oling va 3 formatga moslang: A4 varaqa, kvadrat post va vertikal story (UI uchun — kompyuter, planshet, telefon). Har biriga setka quring, oʻqish tartibini saqlang.",
      ru: "Возьмите контент реального проекта и адаптируйте под 3 формата: листовка A4, квадратный пост и вертикальная история (для UI — десктоп, планшет, телефон). Постройте сетку для каждого, сохранив порядок чтения.",
      en: "Take real project content and adapt it to 3 formats: A4 flyer, square post and vertical story (for UI: desktop, tablet, phone). Build a grid for each and keep the reading order.",
    },
    successCriteria: {
      uz: "3 ta maket setkada qurilgan, oʻqish tartibi bir xil, hech narsa kesilmagan.",
      ru: "3 макета на сетках, порядок чтения одинаков, ничего не обрезано.",
      en: "3 layouts built on grids, same reading order, nothing cropped.",
    },
    why: {
      uz: "Formatlar orasida moslashtirish setka mantiqini tushunganingizni, shunchaki nusxa koʻchirmaganingizni koʻrsatadi.",
      ru: "Адаптация между форматами показывает, что вы понимаете логику сетки, а не копируете раскладку.",
      en: "Adapting across formats shows you understand grid logic rather than copying a layout.",
    },
    resources: [],
  },
  {
    slug: "lg_grid_audit_own_work",
    skill: "layout_grids",
    kind: "verify",
    phase: "verification",
    durationMinutes: 25,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Oʻz ishlaringizda setka auditini oʻtkazing",
      ru: "Проведите аудит сетки в своих работах",
      en: "Audit the grid in your own work",
    },
    description: {
      uz: "Oxirgi 3 ta maketingiz ustiga setkani yoqing. Setkadan chiqqan yoki tizimdan tashqari boʻshliqli har bir elementni belgilang. Tuzating va xatolar sonini avval va keyin yozing.",
      ru: "Включите сетку поверх 3 последних макетов. Отметьте каждый элемент, выпадающий из сетки или с отступом вне системы. Исправьте и запишите число отклонений до и после.",
      en: "Turn on the grid over your last 3 layouts. Mark every element that is off-grid or uses non-system spacing. Fix them and record the count before and after.",
    },
    successCriteria: {
      uz: "Avval/keyin soni yozilgan, sababsiz chetlanish qolmagan.",
      ru: "Записано число до и после, необъяснённых отклонений не осталось.",
      en: "Before/after counts recorded and no unexplained deviations remain.",
    },
    why: {
      uz: "Raqamli audit setka bilan ishlash odatga aylanganini oʻlchanadigan tarzda koʻrsatadi.",
      ru: "Аудит с цифрами измеримо показывает, что работа с сеткой стала привычкой.",
      en: "A counted audit shows measurably that grid discipline has become a habit.",
    },
    resources: [],
  },
];
