import type { ActionInput } from "./_types";

/** Actions for designer.typography (gate K3). */
export const actions: ActionInput[] = [
  {
    slug: "ty_compare_two_typefaces",
    skill: "typography",
    kind: "learn",
    phase: "foundation",
    durationMinutes: 15,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Ikki shriftni yonma-yon solishtirib tahlil qiling",
      ru: "Сравните два шрифта бок о бок",
      en: "Compare two typefaces side by side",
    },
    description: {
      uz: "Bitta serifli va bitta seriflarsiz shrift tanlang. Bir xil abzatsni oʻzbek (lotin) va rus (kirill) tilida tering. Kichik harflar balandligi, harf kengligi, «oʻ» va «gʻ» belgilari koʻrinishi, telefondagi oʻqilishini yozing.",
      ru: "Выберите один шрифт с засечками и один без. Наберите одинаковый абзац на узбекском (латиница) и русском (кириллица). Запишите высоту строчных, ширину знаков, вид «oʻ» и «gʻ», читаемость на телефоне.",
      en: "Pick one serif and one sans-serif face. Set the same paragraph in Uzbek (Latin) and Russian (Cyrillic). Note x-height, letter width, how «oʻ» and «gʻ» render, and readability on a phone.",
    },
    successCriteria: {
      uz: "Kamida 4 ta farq va har bir shrift qayerda mos kelishi yozilgan.",
      ru: "Записаны минимум 4 отличия и где уместен каждый шрифт.",
      en: "At least 4 differences noted, plus where each typeface fits.",
    },
    why: {
      uz: "Shrift tanlash farqlarni koʻrishdan boshlanadi. Ikki yozuvni qoʻllash mahalliy loyihalarda koʻp uchraydigan talab.",
      ru: "Выбор шрифта начинается с умения видеть различия, а поддержка двух алфавитов — частое требование местных проектов.",
      en: "Choosing type starts with seeing differences, and two-script support is a common local requirement.",
    },
    resources: [],
  },
  {
    slug: "ty_build_type_scale",
    skill: "typography",
    kind: "practice",
    phase: "practice",
    durationMinutes: 25,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Matn uchun 4 darajali shrift shkalasini tuzing",
      ru: "Постройте 4-уровневую шрифтовую шкалу",
      en: "Build a 4-step type scale for one text",
    },
    description: {
      uz: "Maqola yoki menyu matnini oling. Sarlavha, kichik sarlavha, asosiy matn va izoh uchun oʻlchamlarni bitta nisbat bilan belgilang (masalan, 1.25). Asosiy matn uchun satr oraligʻi 1.4–1.6, satr uzunligi 45–75 belgi boʻlsin.",
      ru: "Возьмите текст статьи или меню. Задайте размеры заголовка, подзаголовка, основного текста и подписи с одним коэффициентом (например, 1.25). Для основного текста — интерлиньяж 1.4–1.6, длина строки 45–75 знаков.",
      en: "Take an article or menu text. Set heading, subheading, body and caption sizes with one ratio (e.g. 1.25). Give body text 1.4–1.6 line height and 45–75 characters per line.",
    },
    successCriteria: {
      uz: "Sahifada 4 ta aniq farqlanadigan daraja bor, 2 tadan ortiq shrift oilasi ishlatilmagan.",
      ru: "На странице 4 чётко различимых уровня, не более 2 гарнитур.",
      en: "The page has 4 clearly distinct levels and no more than 2 type families.",
    },
    why: {
      uz: "Tizimli shkala tasodifiy oʻlchamlarsiz ierarxiya yaratadi va keyingi qarorlarni tezlashtiradi.",
      ru: "Системная шкала создаёт иерархию без случайных размеров и ускоряет дальнейшие решения.",
      en: "A systematic scale creates hierarchy without random sizes and speeds up later decisions.",
    },
    resources: [],
  },
  {
    slug: "ty_fix_micro_typography",
    skill: "typography",
    kind: "practice",
    phase: "practice",
    durationMinutes: 20,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Matn blokidagi mayda tipografik xatolarni tuzating",
      ru: "Исправьте ошибки микротипографики в тексте",
      en: "Fix micro-typography in a text block",
    },
    description: {
      uz: "Matnga boy maketni oling. Oxirgi satrda yolgʻiz qolgan soʻzlar, notekis chet, qoʻsh boʻshliq, notoʻgʻri qoʻshtirnoq (« » oʻrniga oddiy belgi) va chiziqcha/tire aralashuvini toping. Tuzating va roʻyxat qiling.",
      ru: "Возьмите макет с большим количеством текста. Найдите висячие слова в последней строке, рваный край, двойные пробелы, неверные кавычки (прямые вместо « ») и путаницу дефиса и тире. Исправьте и составьте список.",
      en: "Take a text-heavy layout. Find lone words on last lines, ragged edges, double spaces, wrong quotes and hyphen/dash mix-ups. Fix them and keep a list.",
    },
    successCriteria: {
      uz: "Kamida 5 ta tuzatish roʻyxatda, sarlavhalarda oxirgi satrda yolgʻiz soʻz qolmagan.",
      ru: "В списке не меньше 5 исправлений, в заголовках нет висячих слов.",
      en: "At least 5 fixes listed and no headline ends with a lone word.",
    },
    why: {
      uz: "Mayda tipografik detallar ishning professional koʻrinishini belgilaydi va mijoz ishonchiga taʼsir qiladi.",
      ru: "Детали микротипографики отличают профессиональную работу и влияют на доверие заказчика.",
      en: "Micro-typography details make work look professional and shape client trust.",
    },
    resources: [],
  },
  {
    slug: "ty_bilingual_menu_setting",
    skill: "typography",
    kind: "apply",
    phase: "application",
    durationMinutes: 45,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Ikki tilli menyu yoki narxlar roʻyxatini tering",
      ru: "Сверстайте двуязычное меню или прайс",
      en: "Set a bilingual menu or price list",
    },
    description: {
      uz: "Real yoki realga yaqin oʻzbek-rus menyusini tering: ikkala yozuvni qoʻllaydigan shrift oilasini tanlang, narxlarni (soʻm) bir chiziqqa tekislang, uzun ruscha soʻzlarni boshqaring. Natijani haqiqiy oʻlchamda koʻring.",
      ru: "Сверстайте реальное или реалистичное узбекско-русское меню: выберите гарнитуру с поддержкой обоих алфавитов, выровняйте цены (в сумах), справьтесь с длинными русскими словами. Проверьте в натуральную величину.",
      en: "Set a real or realistic Uzbek-Russian menu: choose a family supporting both scripts, align prices (in soʻm), handle long Russian words. Check it at actual size.",
    },
    successCriteria: {
      uz: "Ikki til bir xil vizual vaznda, narxlar tekis, haqiqiy oʻlchamda oson oʻqiladi.",
      ru: "Оба языка одного визуального веса, цены выровнены, текст легко читается в реальном размере.",
      en: "Both languages carry equal visual weight, prices align, and it reads easily at real size.",
    },
    why: {
      uz: "Ikki tilli matn mahalliy bozordagi kundalik vazifa va tipografik qarorlarni real sharoitda sinaydi.",
      ru: "Двуязычный набор — повседневная задача местного рынка и проверка типографики в реальных условиях.",
      en: "Bilingual setting is everyday work locally and tests type decisions under real constraints.",
    },
    resources: [],
  },
  {
    slug: "ty_readability_ab_check",
    skill: "typography",
    kind: "verify",
    phase: "verification",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Tipografik tanlovingizni oʻqish testida isbotlang",
      ru: "Докажите выбор типографики тестом чтения",
      en: "Prove your type choices with a reading test",
    },
    description: {
      uz: "Bir xil matnning 2 versiyasini (avval va tipografikangizdan keyin) 3 kishiga telefonda koʻrsating. Muayyan maʼlumotni (narx, sana) topish vaqtini oʻlchang va qaysi biri oson oʻqilishini soʻrang. Jadvalga yozing.",
      ru: "Покажите 3 людям на телефоне 2 версии одного текста (до и после вашей типографики). Засеките, за сколько они находят нужное (цена, дата), и спросите, что читается легче. Запишите в таблицу.",
      en: "Show 3 people two versions of the same text on a phone (before and after your typography). Time how fast they find a fact (price, date) and ask which reads easier. Log it in a table.",
    },
    successCriteria: {
      uz: "Jadvalda vaqtlar bor, sizning versiyangizda 3 kishidan kamida 2 tasi maʼlumotni tezroq topgan.",
      ru: "В таблице есть замеры, в вашей версии минимум 2 из 3 нашли информацию быстрее.",
      en: "Timings are logged and at least 2 of 3 found the fact faster in your version.",
    },
    why: {
      uz: "Oʻqilish oʻlchanadigan narsa. Dalil bilan asoslangan tipografika yuqori darajalar uchun kerakli ishonchni beradi.",
      ru: "Читаемость измерима. Типографика, подтверждённая фактами, даёт уверенность для следующих уровней.",
      en: "Readability is measurable; type decisions backed by evidence build confidence for higher levels.",
    },
    resources: [],
  },
];
