import type { ActionInput } from "./_types";

/** Actions for designer.user_research. */
export const actions: ActionInput[] = [
  {
    slug: "ur_observe_real_task",
    skill: "user_research",
    kind: "learn",
    phase: "foundation",
    durationMinutes: 20,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Bir kishining ilovadan foydalanishini kuzating",
      ru: "Понаблюдайте, как человек пользуется приложением",
      en: "Watch one person complete a real app task",
    },
    description: {
      uz: "Tanishingizdan oʻzi ishlatadigan ilovada real vazifani bajarishni soʻrang (Click yoki Payme orqali toʻlov, taksi chaqirish). Yordam bermang. U qayerda ikkilanishi, xato bosishi va nima deyishini yozing.",
      ru: "Попросите знакомого выполнить реальную задачу в привычном приложении (оплата через Click или Payme, вызов такси). Не помогайте. Записывайте, где он сомневается, промахивается и что говорит.",
      en: "Ask someone to do a real task in an app they use (pay via Click or Payme, call a taxi). Do not help. Note where they hesitate, mis-tap and what they say.",
    },
    successCriteria: {
      uz: "Kamida 3 ta ikkilanish holati fikr emas, fakt sifatida yozilgan.",
      ru: "Записаны минимум 3 момента затруднения — как факты, а не мнения.",
      en: "At least 3 moments of hesitation recorded as facts, not opinions.",
    },
    why: {
      uz: "Odamlar aytgan gapdan koʻra qilgan ishi ishonchliroq. Kuzatish tadqiqotning asosi.",
      ru: "Поведение надёжнее слов. Наблюдение — фундамент исследования.",
      en: "What people do is more reliable than what they say; observation is the base of research.",
    },
    resources: [],
  },
  {
    slug: "ur_write_interview_guide",
    skill: "user_research",
    kind: "practice",
    phase: "practice",
    durationMinutes: 25,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "5 ta ochiq savoldan iborat intervyu rejasini yozing",
      ru: "Напишите гайд интервью из 5 открытых вопросов",
      en: "Write a 5-question open interview guide",
    },
    description: {
      uz: "Mahsulot gʻoyasi uchun oʻtmishdagi xatti-harakat haqida 5 ta ochiq savol yozing («Oxirgi marta … qanday qildingiz?»). «Ha/yoʻq», yoʻnaltiruvchi va kelajak haqidagi savollardan qoching. Hamkasbga tekshirtiring.",
      ru: "Для идеи продукта напишите 5 открытых вопросов о прошлом опыте («Как вы в последний раз…?»). Избегайте вопросов «да/нет», наводящих и о будущем. Попросите коллегу проверить.",
      en: "For a product idea, write 5 open questions about past behaviour ('Tell me about the last time you…'). Avoid yes/no, leading and future questions. Have a peer review them.",
    },
    successCriteria: {
      uz: "5 ta savolning birortasi ham «ha/yoʻq» yoki yoʻnaltiruvchi emas, hamkasb tasdiqlagan.",
      ru: "Ни один из 5 вопросов не закрытый и не наводящий, коллега подтвердил.",
      en: "None of the 5 questions is yes/no or leading, confirmed by a peer.",
    },
    why: {
      uz: "Savol notoʻgʻri tuzilsa, javob ham notoʻgʻri boʻladi va dizayn xato asosga quriladi.",
      ru: "Неверно заданный вопрос даёт неверный ответ, и дизайн строится на ложной основе.",
      en: "Badly framed questions produce misleading answers, and the design rests on a false base.",
    },
    resources: [],
  },
  {
    slug: "ur_affinity_synthesis",
    skill: "user_research",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Tadqiqot qaydlarini mavzular boʻyicha guruhlang",
      ru: "Сгруппируйте заметки исследования по темам",
      en: "Cluster research notes into themes",
    },
    description: {
      uz: "Har bir kuzatuvni alohida stikerga yozing (qogʻozda yoki raqamli doskada). Ularni mavzular boʻyicha guruhlang va har bir guruhni foydalanuvchi ehtiyoji sifatida nomlang.",
      ru: "Запишите каждое наблюдение на отдельный стикер (на бумаге или цифровой доске). Сгруппируйте по темам и назовите каждую группу как потребность пользователя.",
      en: "Write each observation on its own sticky note (paper or digital board). Group them by theme and name each group as a user need.",
    },
    successCriteria: {
      uz: "Kamida 3 ta nomlangan mavzu bor, har birida turli odamlardan kamida 2 ta kuzatuv.",
      ru: "Есть минимум 3 названные темы, в каждой — не меньше 2 наблюдений от разных людей.",
      en: "At least 3 named themes, each with 2+ observations from different people.",
    },
    why: {
      uz: "Xom qaydlar qaror bermaydi. Guruhlash takrorlanuvchi ehtiyojlarni ochib, dizayn yoʻnalishini koʻrsatadi.",
      ru: "Сырые заметки не дают решений. Группировка выявляет повторяющиеся потребности и направление дизайна.",
      en: "Raw notes do not drive decisions; clustering surfaces repeated needs and design direction.",
    },
    resources: [],
  },
  {
    slug: "ur_three_person_usability_test",
    skill: "user_research",
    kind: "apply",
    phase: "application",
    durationMinutes: 60,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "3 kishi bilan foydalanish testini oʻtkazing",
      ru: "Проведите юзабилити-тест с 3 участниками",
      en: "Run a usability test with 3 people",
    },
    description: {
      uz: "Prototip yoki mavjud ekran uchun 2–3 ta vazifa tayyorlang. 3 ishtirokchidan fikrini ovoz chiqarib aytib bajarishni soʻrang. Har vazifa boʻyicha natija (bajardi/bajara olmadi) va vaqtni yozing.",
      ru: "Подготовьте 2–3 задачи на прототипе или готовом экране. Попросите 3 участников выполнять их, проговаривая мысли вслух. Записывайте результат (справился/нет) и время по каждой задаче.",
      en: "Prepare 2–3 tasks on a prototype or live screen. Ask 3 participants to do them while thinking aloud. Record success or failure and time for each task.",
    },
    successCriteria: {
      uz: "Ishtirokchilar boʻyicha natijalar jadvali va chastota hamda jiddiylik boʻyicha saralangan 3 ta asosiy muammo bor.",
      ru: "Есть таблица результатов по участникам и 3 главные проблемы, отсортированные по частоте и серьёзности.",
      en: "A results table per participant and the top 3 issues ranked by frequency and severity.",
    },
    why: {
      uz: "Hatto kichik test ham jamoa koʻrmagan muammolarni ochadi va interfeys qarorlarini dalilga tayantiradi.",
      ru: "Даже небольшой тест выявляет проблемы, которых не видит команда, и даёт опору интерфейсным решениям.",
      en: "Even a small test reveals issues the team cannot see and grounds interface decisions in evidence.",
    },
    resources: [],
  },
  {
    slug: "ur_finding_to_design_retest",
    skill: "user_research",
    kind: "verify",
    phase: "verification",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Tadqiqot xulosasini dizayn oʻzgarishiga aylantiring",
      ru: "Превратите вывод исследования в правку дизайна",
      en: "Turn one finding into a tested design change",
    },
    description: {
      uz: "Eng muhim topilmani tanlang va dizaynni shunga qarab oʻzgartiring. Xuddi shu vazifani 2 ta yangi odam bilan qayta sinang. Avvalgi va yangi natijani solishtiring.",
      ru: "Выберите главный вывод и измените дизайн. Повторите ту же задачу с 2 новыми людьми. Сравните результат до и после.",
      en: "Pick the top finding and change the design. Re-run the same task with 2 new people. Compare before and after results.",
    },
    successCriteria: {
      uz: "Avval/keyin natijasi yozilgan: vazifa bajarilishi yaxshilangan yoki nima uchun yaxshilanmagani asoslangan.",
      ru: "Результат до/после записан: выполнение задачи улучшилось, или причина, почему нет, задокументирована.",
      en: "Before/after recorded: task success improved, or the reason it did not is documented.",
    },
    why: {
      uz: "Tadqiqot qiymati u oʻzgartirgan qarorda. Qayta test oʻzgarish haqiqatan yordam berganini isbotlaydi.",
      ru: "Ценность исследования — в решениях, которые оно меняет. Повторный тест доказывает, что правка помогла.",
      en: "Research is worth the decisions it changes; a retest proves the change actually helped.",
    },
    resources: [],
  },
];
