import type { ActionInput } from "./_types";

/** Actions for designer.visual_fundamentals (gate K1). */
export const actions: ActionInput[] = [
  {
    slug: "vf_squint_test_three_designs",
    skill: "visual_fundamentals",
    kind: "reflect",
    phase: "foundation",
    durationMinutes: 15,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Uchta tayyor dizaynni koʻz qisib tahlil qiling",
      ru: "Разберите 3 чужих макета методом прищура",
      en: "Squint-test three existing designs",
    },
    description: {
      uz: "Sizga yoqqan 3 ta afisha yoki ekranni tanlang. Koʻzingizni qisib yoki skrinshotni xiralashtirib qarang. Har biri uchun yozing: birinchi, ikkinchi, uchinchi nima koʻrinadi va buni nima taʼminlagan — oʻlcham, rang, kontrast yoki boʻshliq.",
      ru: "Выберите 3 понравившиеся афиши или экрана. Прищурьтесь или размойте скриншот. Для каждого запишите, что видно первым, вторым, третьим и за счёт чего: размер, цвет, контраст или пустое пространство.",
      en: "Pick 3 posters or screens you like. Squint or blur a screenshot. For each, note what you see first, second and third, and what creates that order: size, colour, contrast or space.",
    },
    successCriteria: {
      uz: "3 ta dizayn uchun eʼtibor tartibi va uning sababi yozilgan.",
      ru: "Для 3 макетов записан порядок внимания и его причина.",
      en: "Attention order and its cause written down for all 3 designs.",
    },
    why: {
      uz: "Ierarxiya vizual asoslarning oʻzagi. Uni oʻzgalar ishida koʻrishni oʻrgansangiz, oʻz maketingizda ham tezroq quradigan boʻlasiz.",
      ru: "Иерархия — ядро визуальных основ. Научившись видеть её в чужих работах, вы быстрее выстроите её в своих.",
      en: "Hierarchy is the core of visual fundamentals. Seeing it in others' work trains you to build it in yours.",
    },
    resources: [],
  },
  {
    slug: "vf_grayscale_hierarchy_fix",
    skill: "visual_fundamentals",
    kind: "practice",
    phase: "practice",
    durationMinutes: 25,
    minLevel: 1,
    maxLevel: 4,
    budget: "free",
    title: {
      uz: "Maketingizni oq-qora rangda tekshirib tuzating",
      ru: "Проверьте и исправьте макет в оттенках серого",
      en: "Fix a layout's hierarchy in grayscale",
    },
    description: {
      uz: "Oʻz maketlaringizdan birini oq-qora rangga oʻtkazing. Asosiy xabar ajralib turmasa, uni rangsiz tuzating: faqat oʻlcham, shrift qalinligi va boʻshliq bilan. Avvalgi va keyingi holatni yonma-yon saqlang.",
      ru: "Переведите один свой макет в оттенки серого. Если главное сообщение не выделяется, исправьте его без цвета — только размером, начертанием и отступами. Сохраните версии «до» и «после» рядом.",
      en: "Convert one of your layouts to grayscale. If the main message does not stand out, fix it without colour, using only size, weight and space. Keep before and after side by side.",
    },
    successCriteria: {
      uz: "Oq-qora variantni koʻrgan odam asosiy elementni 3 soniyada birinchi boʻlib koʻrsatadi.",
      ru: "Человек, увидевший серый вариант, за 3 секунды первым называет главный элемент.",
      en: "Someone shown the grayscale version points to the main element first within 3 seconds.",
    },
    why: {
      uz: "Faqat rangga tayangan ierarxiya tez buziladi. Ton va oʻlcham bilan qurilgan ierarxiya har qanday rangda ishlaydi.",
      ru: "Иерархия, держащаяся только на цвете, легко ломается. Построенная на тоне и размере работает в любой палитре.",
      en: "Hierarchy that relies on colour alone breaks easily; tone and size make it hold in any palette.",
    },
    resources: [],
  },
  {
    slug: "vf_three_composition_variants",
    skill: "visual_fundamentals",
    kind: "practice",
    phase: "practice",
    durationMinutes: 30,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Bitta eʼlonning 3 xil kompozitsiyasini yarating",
      ru: "Сделайте 3 композиции одного объявления",
      en: "Make 3 compositions of one promo",
    },
    description: {
      uz: "Bir xil matn va rasm oling (masalan, kafe aksiyasi). 3 variant yarating: simmetrik, asimmetrik va katta boʻsh joyli. Eng kuchlisini tanlang va nima uchun aynan u maqsadga mosligini 2 jumlada yozing.",
      ru: "Возьмите один и тот же текст и фото (например, акция кафе). Сделайте 3 варианта: симметричный, асимметричный и с большим пустым пространством. Выберите сильнейший и в 2 предложениях объясните, почему он лучше решает задачу.",
      en: "Use the same copy and image (e.g. a café promo). Make 3 versions: symmetric, asymmetric and one with lots of empty space. Pick the strongest and explain in 2 sentences why it fits the goal best.",
    },
    successCriteria: {
      uz: "3 ta variant tayyor, tanlov maqsadga bogʻlangan sabab bilan yozilgan.",
      ru: "Готовы 3 варианта, выбор объяснён через цель, а не вкус.",
      en: "3 variants exist and the choice is justified by the goal, not taste.",
    },
    why: {
      uz: "Birinchi gʻoyada toʻxtamasdan variantlarni solishtirish kompozitsiya boʻyicha mustaqil qaror qabul qilishni rivojlantiradi.",
      ru: "Сравнение вариантов вместо первой идеи развивает самостоятельные композиционные решения.",
      en: "Comparing options instead of keeping the first idea builds independent compositional judgment.",
    },
    resources: [],
  },
  {
    slug: "vf_palette_contrast_roles",
    skill: "visual_fundamentals",
    kind: "apply",
    phase: "application",
    durationMinutes: 45,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Real loyiha palitrasini kontrastga tekshiring",
      ru: "Проверьте палитру реального проекта на контраст",
      en: "Audit a live project's palette for contrast",
    },
    description: {
      uz: "Joriy loyiha palitrasini oling. Har bir matn/fon juftligini kontrast tekshirgichda tekshiring. Oʻtmaganlarini almashtiring va har rangga rol bering: asosiy, urgʻu, fon, matn, xato. Yangilangan palitrani maketga qoʻllang.",
      ru: "Возьмите палитру текущего проекта. Проверьте каждую пару «текст/фон» в инструменте проверки контраста. Замените непрошедшие и назначьте цветам роли: основной, акцент, фон, текст, ошибка. Примените к макету.",
      en: "Take your current project's palette. Check every text/background pair with a contrast checker. Replace failing pairs and give each colour a role: primary, accent, background, text, error. Apply it to the layout.",
    },
    successCriteria: {
      uz: "Asosiy matn juftliklari WCAG AA (4.5:1) talabiga javob beradi, har rangning roli yozilgan.",
      ru: "Пары основного текста соответствуют WCAG AA (4.5:1), у каждого цвета записана роль.",
      en: "Body text pairs meet WCAG AA (4.5:1) and every colour has a written role.",
    },
    why: {
      uz: "Rang tasodifiy tanlansa, ierarxiya va oʻqilishi buziladi. Rollar va kontrast rangni boshqariladigan vositaga aylantiradi.",
      ru: "Случайные цвета ломают иерархию и читаемость. Роли и контраст превращают цвет в управляемый инструмент.",
      en: "Random colours break hierarchy and legibility; roles and contrast turn colour into a controlled tool.",
    },
    resources: [],
  },
  {
    slug: "vf_five_second_test",
    skill: "visual_fundamentals",
    kind: "verify",
    phase: "verification",
    durationMinutes: 20,
    minLevel: 4,
    maxLevel: 8,
    budget: "free",
    title: {
      uz: "Maketni 5 soniyalik test bilan tekshiring",
      ru: "Проверьте макет 5-секундным тестом",
      en: "Run a 5-second test on a layout",
    },
    description: {
      uz: "Tayyor maketni 3 kishiga 5 soniya koʻrsatib, yashiring. Soʻrang: bu nima haqida edi, birinchi nima esda qoldi, nima qilish kerak edi? Javoblarni siz rejalashtirgan ierarxiya bilan solishtiring.",
      ru: "Покажите готовый макет 3 людям на 5 секунд и скройте. Спросите: о чём это, что запомнилось первым, что нужно сделать? Сравните ответы с задуманной иерархией.",
      en: "Show a finished layout to 3 people for 5 seconds, then hide it. Ask: what was it about, what did you notice first, what should you do? Compare answers with your intended hierarchy.",
    },
    successCriteria: {
      uz: "3 kishidan kamida 2 tasi asosiy xabar va kutilgan harakatni toʻgʻri aytadi.",
      ru: "Минимум 2 из 3 человек верно называют главное сообщение и нужное действие.",
      en: "At least 2 of 3 people name the main message and intended action correctly.",
    },
    why: {
      uz: "Ierarxiya faqat sizning tasavvuringizda emas, begona koʻzda ham ishlashini isbotlaydi.",
      ru: "Доказывает, что иерархия работает не только в вашей голове, но и для свежего взгляда.",
      en: "Proves the hierarchy works for fresh eyes, not only in your head.",
    },
    resources: [],
  },
];
